import 'package:flutter/material.dart';
import 'package:payvessel_mobile_app/utils_size.dart';

const background = Color(0xFFffffff);
const dashboardBg = Color(0xFFf5f5f5);
const appbg = Color(0xFFFAFAFA);
const profileFieldColor = Color(0xfff6f6f6);
const compliancePink = Color(0xffffe7d6);
const white = Color(0xFFffffff);
const lighterGreen = Color(0xffdff1e2);
const green = Color(0xff14b22a);
const orange = Color(0xFFff6b00);
const lightOrange = Color(0xFFff9040);
const pink = Color(0xFFffb580);
const lightPink = Color(0xFFffdabf);
const lighterPink = Color(0xFFfff8f2);
const black = Color(0xFF050505);
const lightBlack = Color(0xFF444444);
const grey = Color(0xFF828282);
const grey1 = Color(0xff434343);
const lightGrey = Color(0xFFc1c1c1);
const lighterGrey = Color(0xFFdddad7);
const transparent = Colors.transparent;
